title: CAT-AI Documentation
description: Documentation for the CAT-AI framework
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
markdown: kramdown
relative_links:
  enabled: true
  collections: true
show_downloads: false
